### ISSUE TITLE
Robot Test Checklist

### ISSUE THREAD

**Issue by SHS-Programmers** [Staley-Robotics/StaleyRC2020#67]
Things we need to test when we get the bot.  Oh man we are so screwed lmao.

- drive train
  - [x]  check that motors are going the correct direction independently
  - [x] verify constants   
  - [x] verify world of tanks works properly
  - [ ] check auto shifting
  - [ ] try squared inputs
- pneumatics
  - [x] check that compressor works
  - [x] verify constants
  - [x] check that pneumatic tubing doesn't leak
  - [x] check PCM 
  - [x] check solenoid block
- intake
  - [x] check that motors are going the correct direction
  - [x] verify constants
  - [x] intake works
  - [ ] intake can be used while driving
  - [x] intake can run backwards
  - [ ] test closedLoop max value
- magazine
  - [x] check that both motors are going the correct direction independently
  - [x] verify constants
  - [x] runs forwards and backwards
  - [x] magazine works
  - [x] check that balls can slip on belt
- mast 
  - [x] check that the motor is going the correct direction
  - [x] verify constants
  - [x] mast can extend and retract
  - [x] mast is running at the desired speed
- winch
  - [x] check that both motors are going the correct direction independently
  - [x] verify constants
  - [x] runs forward and backward
  - [x] both motors are running at the same speed  
- shooter
  - [x] check that both motors are going the correct direction independently
  - [ ] verify constants
  - [ ] shooter has correct arc
  - [ ] speed needed at various distances (use test shooter branch)
- vision
  - [x] starts on startup
  - [ ] verify constants
  - [x] can detect target
  - [ ] produces accurate distance
  - [x] can view stream in shuffleboard
  - [ ] auto align works
- color sensor - **N/A anymore**
  - [ ] color sensor works
  - [ ] verify constants
  - [ ] speed we spin wheel is not too fast
- wheel of fortune spin number - **N/A anymore**
  - [ ] piston goes up and down
  - [ ] verify constants
  - [ ] ratio of spins is accurate
  - [ ] wof guy spins wof
- autos
  - [ ] verify constants
  - [x] auto selector works
  - [ ] the intake and magazine run during autos
  - [ ] recharacterize robot
  - [ ] vision lines up to shooter
  - [ ] shooter makes goals
  - [ ] reverse paths work

**Comment by Dustin-Klein** [comment]
So we didnt get this done before comp because build team bad.  Not much time between now and next comp so I'm closing this issue
